# Retail Analytics Project

## Sprint 1 - Sales Data Analysis

### Module
Sales Data Profiling

### Objective

Understand the Sales dataset before performing any cleaning.

### Author
Jayashree Baskaran

### Date
12-Jul-2026

In [4]:
import pandas as py
import numpy as np
sales = py.read_csv(r"C:\Users\ADMIN\Desktop\Retail_Analytics_Project\02_Raw_Data\Sales_Data.csv")
print (sales.head().to_string())

         Date Site ID Product ID  Units Sold   Revenue  Discounts  Returns Customer ID
0  02-04-2024    XDP5   PRD10002          20   4844.84     764.83        3  CUST200026
1  03-04-2024    PS3Y   PRD10020          27   9001.49    1639.15        3  CUST200048
2  09-04-2024    8CGV   PRD10008          23   3122.03     463.83        0  CUST200025
3  09-04-2024    4CIY   PRD10070          38  11323.57    1275.45        1  CUST200048
4  17-04-2024    2VLP   PRD10019          44  10382.36    1096.84        3  CUST200040

In [12]:
sales.shape

(219, 8)

In [13]:
sales.columns

Index(['Date', 'Site ID', 'Product ID', 'Units Sold', 'Revenue', 'Discounts',
       'Returns', 'Customer ID'],
      dtype='str')

In [15]:
list(sales.columns)

['Date',
 'Site ID',
 'Product ID',
 'Units Sold',
 'Revenue',
 'Discounts',
 'Returns',
 'Customer ID']

In [17]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         219 non-null    str
 1   Site ID      219 non-null    str
 2   Product ID   219 non-null    str
 3   Units Sold   219 non-null    int64
 4   Revenue      219 non-null    float64
 5   Discounts    219 non-null    float64
 6   Returns      219 non-null    int64
 7   Customer ID  219 non-null    str
dtypes: float64(2), int64(2), str(4)
memory usage: 13.8 KB

In [ ]:
## Observation after Data Profiling

- Total Records : 219
- Total Columns : 8
- Missing Values : No missing values found
- Date column is stored as String (Needs conversion to datetime)
- Revenue and Discounts are Decimal
- Units Sold and Returns are Integer
- Dataset size : 13.8 KB

Conclusion:
Dataset quality is good. Only the Date column requires data type conversion.

In [20]:
sales.describe()

       Units Sold       Revenue    Discounts     Returns
count  219.000000    219.000000   219.000000  219.000000
mean    26.073059   6705.041689   824.273242    2.890411
std     14.346759   5617.367440   730.619281    1.677386
min      1.000000    118.120000    21.990000    0.000000
25%     13.000000   1979.210000   252.680000    1.000000
50%     26.000000   5270.540000   594.240000    3.000000
75%     39.000000   9735.120000  1191.880000    4.000000
max     50.000000  24190.350000  2889.210000    5.000000

In [ ]:
## Observation - Descriptive Statistics

- Generated summary statistics for numeric columns.
- Reviewed average, minimum, maximum, and spread of values.
- Checked for unusually high or low values.
- This helps identify possible outliers before further analysis.

In [22]:
sales.describe().T

,count,mean,std,min,25%,50%,75%,max
Units Sold,219.0,26.073059,14.346759,1.00,13.00,26.00,39.00,50.00
Revenue,219.0,6705.041689,5617.367440,118.12,1979.21,5270.54,9735.12,24190.35
Discounts,219.0,824.273242,730.619281,21.99,252.68,594.24,1191.88,2889.21
Returns,219.0,2.890411,1.677386,0.00,1.00,3.00,4.00,5.00

In [ ]:
## Conclusion

The sales dataset appears consistent.
Revenue has high variation and requires further analysis to identify high-value transactions or possible outliers.

In [23]:
sales.isnull().sum()

Date           0
Site ID        0
Product ID     0
Units Sold     0
Revenue        0
Discounts      0
Returns        0
Customer ID    0
dtype: int64

In [25]:
sales.duplicated().sum()

np.int64(0)

In [26]:
sales.nunique()

Date           166
Site ID         49
Product ID      78
Units Sold      50
Revenue        200
Discounts      200
Returns          6
Customer ID     50
dtype: int64

In [ ]:
## Observation - Unique Values

- Dataset contains 49 retail sites.
- 78 different products were sold.
- 50 unique customers made 219 transactions.
- Sales occurred across 166 different dates.
- Return quantity ranges from 0 to 5.

Conclusion:
Customers made repeat purchases, and the dataset contains sufficient variety for sales trend and customer analysis.

In [27]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         219 non-null    str
 1   Site ID      219 non-null    str
 2   Product ID   219 non-null    str
 3   Units Sold   219 non-null    int64
 4   Revenue      219 non-null    float64
 5   Discounts    219 non-null    float64
 6   Returns      219 non-null    int64
 7   Customer ID  219 non-null    str
dtypes: float64(2), int64(2), str(4)
memory usage: 13.8 KB

In [28]:
# changeing the date datatype

In [31]:
sales["Date"] = py.to_datetime(
    sales["Date"],
    format="%d-%m-%Y"
)

In [32]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         219 non-null    datetime64[us]
 1   Site ID      219 non-null    str
 2   Product ID   219 non-null    str
 3   Units Sold   219 non-null    int64
 4   Revenue      219 non-null    float64
 5   Discounts    219 non-null    float64
 6   Returns      219 non-null    int64
 7   Customer ID  219 non-null    str
dtypes: datetime64[us](1), float64(2), int64(2), str(3)
memory usage: 13.8 KB

In [35]:
sales["Date"].head().info()

<class 'pandas.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: Date
Non-Null Count  Dtype
--------------  -----
5 non-null      datetime64[us]
dtypes: datetime64[us](1)
memory usage: 172.0 bytes

In [36]:
sales["Date"].head()

0   2024-04-02
1   2024-04-03
2   2024-04-09
3   2024-04-09
4   2024-04-17
Name: Date, dtype: datetime64[us]

In [37]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         219 non-null    datetime64[us]
 1   Site ID      219 non-null    str
 2   Product ID   219 non-null    str
 3   Units Sold   219 non-null    int64
 4   Revenue      219 non-null    float64
 5   Discounts    219 non-null    float64
 6   Returns      219 non-null    int64
 7   Customer ID  219 non-null    str
dtypes: datetime64[us](1), float64(2), int64(2), str(3)
memory usage: 13.8 KB

In [43]:
#data validation checking negative value, zero, invalid vlaues, missing values

sales[sales["Discounts"]<0]

Empty DataFrame
Columns: [Date, Site ID, Product ID, Units Sold, Revenue, Discounts, Returns, Customer ID]
Index: []

In [42]:
sales[sales["Units Sold"]<=0]

Empty DataFrame
Columns: [Date, Site ID, Product ID, Units Sold, Revenue, Discounts, Returns, Customer ID]
Index: []

In [44]:
sales[sales["Revenue"]<=0]

Empty DataFrame
Columns: [Date, Site ID, Product ID, Units Sold, Revenue, Discounts, Returns, Customer ID]
Index: []

In [46]:
sales[sales["Returns"] > sales["Units Sold"]]

,Date,Site ID,Product ID,Units Sold,Revenue,Discounts,Returns,Customer ID
65,2024-07-20,P7Y6,PRD10045,4,177.04,21.99,5,CUST200019
166,2025-01-21,SV87,PRD10092,4,1200.36,90.72,5,CUST200032
196,2025-03-25,H75L,PRD10024,2,463.40,52.28,3,CUST200034
215,2025-05-08,H75L,PRD10024,2,463.40,52.28,3,CUST200034

In [47]:
sales[sales["Returns"] > sales["Units Sold"]].shape

(4, 8)

In [48]:
invalid_returns = sales[sales["Returns"] > sales["Units Sold"]]
invalid_returns

,Date,Site ID,Product ID,Units Sold,Revenue,Discounts,Returns,Customer ID
65,2024-07-20,P7Y6,PRD10045,4,177.04,21.99,5,CUST200019
166,2025-01-21,SV87,PRD10092,4,1200.36,90.72,5,CUST200032
196,2025-03-25,H75L,PRD10024,2,463.40,52.28,3,CUST200034
215,2025-05-08,H75L,PRD10024,2,463.40,52.28,3,CUST200034

In [ ]:
## Business Validation - Returns

Business Rule:
Returns should never exceed Units Sold for a transaction.

Observation:
Found records where Returns > Units Sold.

Action:
Flagged these records for business review.
No records were modified at this stage.

In [51]:
invalid_returns = sales[sales["Returns"] > sales["Units Sold"]]

invalid_returns.shape

(4, 8)

In [52]:
sales[sales["Returns"] > sales["Units Sold"]]

,Date,Site ID,Product ID,Units Sold,Revenue,Discounts,Returns,Customer ID
65,2024-07-20,P7Y6,PRD10045,4,177.04,21.99,5,CUST200019
166,2025-01-21,SV87,PRD10092,4,1200.36,90.72,5,CUST200032
196,2025-03-25,H75L,PRD10024,2,463.40,52.28,3,CUST200034
215,2025-05-08,H75L,PRD10024,2,463.40,52.28,3,CUST200034

In [55]:
sales.shape

(219, 8)

In [57]:
sales_clean= sales[sales ["Returns"]<=sales["Units Sold"]]
sales_clean.shape

(215, 8)

In [59]:
print(invalid_returns.shape,
sales_clean.shape)

(4, 8) (215, 8)

In [60]:
sales_clean.to_csv("../03_Cleaned_Data/Sales_Data_Cleaned.csv",index=False)

In [61]:
invalid_returns.to_csv("../03_Cleaned_Data/Invalid_Returns.csv",index=False)

In [69]:
total_revenue=sales_clean["Revenue"].sum()
print(f"Total Revenue: {total_revenue: ,.2f}")

total_sold=sales_clean["Units Sold"].sum()
print(f"Total Unit Sold: {total_sold: ,.2f}")

total_discount = sales_clean["Discounts"].sum()

print(f"Total Discounts : ₹{total_discount:,.2f}")

total_return = sales_clean["Returns"].sum()

print(f"Total Returns : ₹{total_return:,.2f}")

Total Revenue:  1,466,099.93
Total Unit Sold:  5,698.00
Total Discounts : ₹180,298.57
Total Returns : ₹617.00

In [94]:
top_10=sales_clean.groupby("Product ID")["Revenue"].sum().sort_values(ascending=False)
bottom=sales_clean.groupby("Product ID")["Revenue"].sum().sort_values()

revenue =(sales_clean.groupby("Product ID",as_index=False)["Revenue"].sum().sort_values("Revenue",ascending=False))
unitd =sales_clean.groupby("Product ID",as_index=False)["Units Sold"].sum().sort_values("Units Sold",ascending=False)
print(f"Top Product -\n{top_10.head()}")
print(f"Least Product -\n{bottom.head()}")

Top Product -
Product ID
PRD10070    62275.59
PRD10045    62180.00
PRD10023    51299.04
PRD10011    49416.59
PRD10064    42636.29
Name: Revenue, dtype: float64
Least Product -
Product ID
PRD10041     971.17
PRD10062    1025.26
PRD10021    1325.16
PRD10050    1934.64
PRD10065    2891.13
Name: Revenue, dtype: float64

In [95]:
print(f"Revenue -\n{revenue.head(10)}")
print(f"Unit Sold-\n{unitd.head(10)}")

Revenue -
   Product ID   Revenue
54   PRD10070  62275.59
34   PRD10045  62180.00
17   PRD10023  51299.04
7    PRD10011  49416.59
48   PRD10064  42636.29
1    PRD10003  42498.28
39   PRD10052  41475.55
36   PRD10047  40821.51
53   PRD10069  38185.61
45   PRD10059  37491.21
Unit Sold-
   Product ID  Units Sold
1    PRD10003         182
34   PRD10045         180
54   PRD10070         157
48   PRD10064         153
24   PRD10031         151
77   PRD10099         151
7    PRD10011         146
57   PRD10075         140
39   PRD10052         140
45   PRD10059         138

In [86]:
revenue_by_product = (
    sales_clean
    .groupby("Product ID", as_index=False)["Revenue"]
    .sum()
    .sort_values("Revenue", ascending=False)
)

revenue_by_product.head()

   Product ID   Revenue
54   PRD10070  62275.59
34   PRD10045  62180.00
17   PRD10023  51299.04
7    PRD10011  49416.59
48   PRD10064  42636.29

In [104]:
# STORE ANALYSIS BY REVENUE BY STORE,UNIT SOLD BY STORE,RETURN RATE BY STORE
revenue_store=sales_clean.groupby("Site ID",as_index=False)["Revenue"].sum().sort_values("Revenue",ascending=False)
print(f"Revenue by Store\n{revenue_store.head()}")

unit_store=sales_clean.groupby("Site ID",as_index=False)["Units Sold"].sum().sort_values("Units Sold",ascending=False)
print(f"Unit Sold by Store\n{unit_store.head()}")

return_store=sales_clean.groupby("Site ID",as_index=False)["Returns"].sum().sort_values("Returns",ascending=False)
print(f"Revenue by Store\n{return_store.head()}")

Revenue by Store
   Site ID    Revenue
33    M5K8  116252.24
40    PS3Y   89084.51
13    A1WJ   62072.25
1     0RJI   57137.90
8     5JSG   53045.14
Unit Sold by Store
   Site ID  Units Sold
33    M5K8         356
13    A1WJ         308
40    PS3Y         266
48    ZYTJ         191
8     5JSG         186
Revenue by Store
   Site ID  Returns
33    M5K8       34
40    PS3Y       30
48    ZYTJ       28
13    A1WJ       27
8     5JSG       22

In [108]:
store_analysis = (
    sales_clean
    .groupby("Site ID", as_index=False)[["Units Sold", "Returns", "Revenue"]]
    .sum()
)
store_analysis["Return Rate (%)"] = (
    store_analysis["Returns"] /
    store_analysis["Units Sold"]
) * 100


store_analysis.head().sort_values("Revenue", ascending=False)

  Site ID  Units Sold  Returns   Revenue  Return Rate (%)
1    0RJI         179       17  57137.90         9.497207
2    0T0P         127       13  30115.68        10.236220
3    2VLP         151       17  23550.86        11.258278
0    0L72          43        3   8906.55         6.976744
4    30T9         136       13   8658.45         9.558824

In [110]:
store_summary = (
    sales_clean
    .groupby("Site ID", as_index=False)
    .agg({
        "Revenue": "sum",
        "Units Sold": "sum",
        "Returns": "sum"
    })
)

store_summary["Return Rate (%)"] = (
    store_summary["Returns"] /
    store_summary["Units Sold"]
) * 100

store_summary = store_summary.sort_values("Revenue", ascending=False)

store_summary.head()

   Site ID    Revenue  Units Sold  Returns  Return Rate (%)
33    M5K8  116252.24         356       34         9.550562
40    PS3Y   89084.51         266       30        11.278195
13    A1WJ   62072.25         308       27         8.766234
1     0RJI   57137.90         179       17         9.497207
8     5JSG   53045.14         186       22        11.827957

In [1]:
#Customer Analysis
#Number of Transactions by Customer

In [6]:
customer_transactions = (
    sales_clean
    .groupby("Customer ID", as_index=False)["Units Sold"]
    .count()
    .rename(columns={"Units Sold": "No of Transactions"})
    .sort_values("No of Transactions", ascending=False)
)

print(customer_transactions.head(10))

NameError: name 'sales_clean' is not defined

In [5]:
py.read_csv("../03_Cleaned_Data/Sales_Data_Cleaned.csv")

,Date,Site ID,Product ID,Units Sold,Revenue,Discounts,Returns,Customer ID
0,2024-04-02,XDP5,PRD10002,20,4844.84,764.83,3,CUST200026
1,2024-04-03,PS3Y,PRD10020,27,9001.49,1639.15,3,CUST200048
2,2024-04-09,8CGV,PRD10008,23,3122.03,463.83,0,CUST200025
3,2024-04-09,4CIY,PRD10070,38,11323.57,1275.45,1,CUST200048
4,2024-04-17,2VLP,PRD10019,44,10382.36,1096.84,3,CUST200040
...,...,...,...,...,...,...,...,...
210,2025-05-14,4CIY,PRD10078,31,3480.89,302.76,4,CUST200039
211,2025-05-03,GDPP,PRD10003,12,1814.04,298.16,2,CUST200017
212,2025-05-11,CX19,PRD10069,4,1874.40,113.13,3,CUST200021
213,2025-05-14,NY20,PRD10087,34,2205.15,332.03,4,CUST200001
214,2025-05-14,30T9,PRD10031,48,1979.21,229.28,4,CUST200030