In [1]:

import mysql.connector
import pandas as pd


connection = mysql.connector.connect(host="localhost",
                                     
    user="root",
    password="12345" )
if connection.is_connected():
    print("sucessfully connected to sql")

sucessfully connected to sql

In [2]:
cursor=connection.cursor()
# create data base
cursor.execute("CREATE DATABASE if not exists Retail_Analytics_DB")
cursor.execute("USE Retail_Analytics_DB")

In [3]:
product = pd.read_csv(
    r"C:\Users\ADMIN\Desktop\Retail_Analytics_Project\03_Cleaned_Data\Product_Data_Cleaned.csv"
)

In [4]:
product.head()

,Product ID,Product Name,Category,Subcategory,Unit Cost,Unit Price,Supplier,Shelf Life
0,PRD10000,Cheese Item 0,Dairy,Cheese,127.63,143.90,Supplier 1,12
1,PRD10001,Bread Item 1,Bakery,Bread,422.83,570.20,Supplier 4,37
2,PRD10002,Accessories Item 2,Electronics,Accessories,74.91,110.80,Supplier 8,70
3,PRD10003,Men Item 3,Apparel,Men,310.83,461.74,Supplier 2,46
4,PRD10004,Men Item 4,Apparel,Men,297.77,438.18,Supplier 10,178

In [5]:
product.head()

,Product ID,Product Name,Category,Subcategory,Unit Cost,Unit Price,Supplier,Shelf Life
0,PRD10000,Cheese Item 0,Dairy,Cheese,127.63,143.90,Supplier 1,12
1,PRD10001,Bread Item 1,Bakery,Bread,422.83,570.20,Supplier 4,37
2,PRD10002,Accessories Item 2,Electronics,Accessories,74.91,110.80,Supplier 8,70
3,PRD10003,Men Item 3,Apparel,Men,310.83,461.74,Supplier 2,46
4,PRD10004,Men Item 4,Apparel,Men,297.77,438.18,Supplier 10,178

In [6]:
product.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product ID    100 non-null    str
 1   Product Name  100 non-null    str
 2   Category      100 non-null    str
 3   Subcategory   100 non-null    str
 4   Unit Cost     100 non-null    float64
 5   Unit Price    100 non-null    float64
 6   Supplier      100 non-null    str
 7   Shelf Life    100 non-null    int64
dtypes: float64(2), int64(1), str(5)
memory usage: 6.4 KB

In [7]:
product.columns.tolist()

['Product ID',
 'Product Name',
 'Category',
 'Subcategory',
 'Unit Cost',
 'Unit Price',
 'Supplier',
 'Shelf Life']

In [8]:
product.dtypes

Product ID          str
Product Name        str
Category            str
Subcategory         str
Unit Cost       float64
Unit Price      float64
Supplier            str
Shelf Life        int64
dtype: object

In [9]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Product (
    Product_ID VARCHAR(100) PRIMARY KEY,
    Product_Name VARCHAR(100) NOT NULL,
    Category VARCHAR(50) NOT NULL,
    Subcategory VARCHAR(50) NOT NULL,
    Unit_Cost FLOAT NOT NULL,
    Unit_Price FLOAT NOT NULL,
    Supplier VARCHAR(100) NOT NULL,
    Shelf_Life INT NOT NULL
)
""")
connection.commit()

In [10]:
cursor.execute("SHOW TABLES")
for table in cursor:
    print(table)

('product',)
('site',)

In [11]:
cursor.execute("DESCRIBE Product")
for row in cursor.fetchall():
    print(row)

('Product_ID', 'varchar(100)', 'NO', 'PRI', None, '')
('Product_Name', 'varchar(100)', 'NO', '', None, '')
('Category', 'varchar(50)', 'NO', '', None, '')
('Subcategory', 'varchar(50)', 'NO', '', None, '')
('Unit_Cost', 'float', 'NO', '', None, '')
('Unit_Price', 'float', 'NO', '', None, '')
('Supplier', 'varchar(100)', 'NO', '', None, '')
('Shelf_Life', 'int', 'NO', '', None, '')

In [12]:
Customer=pd.read_csv(r"C:\Users\ADMIN\Desktop\Retail_Analytics_Project\03_Cleaned_Data\Customer_Demographics_Cleaned.csv")

In [13]:
Customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          50 non-null     int64
 1   Customer ID         50 non-null     str
 2   Age                 50 non-null     int64
 3   Gender              50 non-null     str
 4   Income Bracket      50 non-null     str
 5   Purchase Frequency  50 non-null     int64
 6   Average Spend       50 non-null     float64
dtypes: float64(1), int64(3), str(3)
memory usage: 2.9 KB

In [14]:
Customer.head(
    
)

,Unnamed: 0,Customer ID,Age,Gender,Income Bracket,Purchase Frequency,Average Spend
0,0,CUST200000,29,Female,10 LPA,9,2248.08
1,1,CUST200001,56,Male,20+ LPA,7,1335.89
2,2,CUST200002,58,Other,10 LPA,9,1250.89
3,3,CUST200003,36,Male,10 LPA,6,4288.93
4,4,CUST200004,57,Male,10-20 LPA,1,2680.74

In [15]:
Customer.dtypes

Unnamed: 0              int64
Customer ID               str
Age                     int64
Gender                    str
Income Bracket            str
Purchase Frequency      int64
Average Spend         float64
dtype: object

In [16]:
cursor.execute("""CREATE TABLE IF NOT EXISTS Customer(Customer_ID varchar(20) PRIMARY KEY,
Age int,
Gender varchar(20),
Income_Bracket varchar(20),
Purchase_Frequency int,
Average_Spend float
)""")
connection.commit()

In [17]:
cursor.execute("SHOW TABLES")
for table in cursor:
 print(table)

('customer',)
('product',)
('site',)

In [18]:
print(connection.is_connected())

True

In [19]:
cursor.execute("DESCRIBE Customer")
for row in cursor.fetchall():
    print(row)

('Customer_ID', 'varchar(20)', 'NO', 'PRI', None, '')
('Age', 'int', 'YES', '', None, '')
('Gender', 'varchar(20)', 'YES', '', None, '')
('Income_Bracket', 'varchar(20)', 'YES', '', None, '')
('Purchase_Frequency', 'int', 'YES', '', None, '')
('Average_Spend', 'float', 'YES', '', None, '')

In [20]:
cursor.execute("DROP TABLE IF EXISTS Customer")
connection.commit()

In [21]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Customer (
    Customer_ID VARCHAR(20) PRIMARY KEY,
    Age INT NOT NULL,
    Gender VARCHAR(20) NOT NULL,
    Income_Bracket VARCHAR(20) NOT NULL,
    Purchase_Frequency INT NOT NULL,
    Average_Spend FLOAT NOT NULL
)
""")

connection.commit()

print("Customer table created successfully")

Customer table created successfully

In [22]:
Site=pd.read_csv(r"C:\Users\ADMIN\Desktop\Retail_Analytics_Project\03_Cleaned_Data\Site_Details_Cleaned.csv")

In [23]:
Site.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Site ID      50 non-null     str
 1   Site Name    50 non-null     str
 2   Site Format  50 non-null     str
 3   Region       50 non-null     str
 4   City         50 non-null     str
 5   State        50 non-null     str
 6   Store Size   50 non-null     int64
 7   Open Date    50 non-null     str
 8   Status       50 non-null     str
dtypes: int64(1), str(8)
memory usage: 3.6 KB

In [24]:
Site["Open Date"]=pd.to_datetime(Site["Open Date"],errors="coerce")

In [25]:
Site.head()

,Site ID,Site Name,Site Format,Region,City,State,Store Size,Open Date,Status
0,JI0Y,Smart Mumbai,Digital,North,Mumbai,Maharashtra,6041,2015-05-03,Active
1,VUZZ,Digital Ahmedabad,Fresh,North,Ahmedabad,Gujarat,19719,2021-08-10,Inactive
2,PKH1,Smart Mumbai,Smart,North,Mumbai,Maharashtra,17449,2016-02-01,Inactive
3,30T9,Digital Hubli,Smart,South,Hubli,Karnataka,23089,2018-04-15,Inactive
4,CX19,Fresh New Delhi,Smart,North,New Delhi,Delhi,17455,2018-02-12,Inactive

In [26]:
Site.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Site ID      50 non-null     str
 1   Site Name    50 non-null     str
 2   Site Format  50 non-null     str
 3   Region       50 non-null     str
 4   City         50 non-null     str
 5   State        50 non-null     str
 6   Store Size   50 non-null     int64
 7   Open Date    50 non-null     datetime64[us]
 8   Status       50 non-null     str
dtypes: datetime64[us](1), int64(1), str(7)
memory usage: 3.6 KB

In [27]:
cursor.execute("DROP TABLE IF EXISTS SITE")
connection.commit()

In [28]:
cursor.execute(""" CREATE TABLE IF NOT EXISTS SITE(
Site_ID VARCHAR(20) PRIMARY KEY,
Site_Name VARCHAR(20) NOT NULL,
Site_Format VARCHAR(20) NOT NULL,
Region VARCHAR(20) NOT NULL,
City VARCHAR(20) NOT NULL,
State VARCHAR(20) NOT NULL,
Store_Size VARCHAR(20) NOT NULL,
Open_Date Date NOT NULL,
Status VARCHAR(20))"""

)

In [29]:
connection.commit()

In [30]:
cursor.execute("SHOW TABLES")
for table in cursor.fetchall():
    print(table)

('customer',)
('product',)
('site',)

In [32]:
cursor.execute("DESCRIBE Site")
for row in cursor.fetchall():
    print(row)

('Site_ID', 'varchar(20)', 'NO', 'PRI', None, '')
('Site_Name', 'varchar(20)', 'NO', '', None, '')
('Site_Format', 'varchar(20)', 'NO', '', None, '')
('Region', 'varchar(20)', 'NO', '', None, '')
('City', 'varchar(20)', 'NO', '', None, '')
('State', 'varchar(20)', 'NO', '', None, '')
('Store_Size', 'varchar(20)', 'NO', '', None, '')
('Open_Date', 'date', 'NO', '', None, '')
('Status', 'varchar(20)', 'YES', '', None, '')

In [33]:
Inventory=pd.read_csv(r"C:\Users\ADMIN\Desktop\Retail_Analytics_Project\03_Cleaned_Data\Inventory_Data_Cleaned.csv")
Inventory.head()

,Site ID,Product ID,Beginning Inventory,Ending Inventory,Replenishment,Stockout Flag,Net Stock
0,A11D,PRD10087,222,233,42,No,11
1,AM14,PRD10082,428,442,72,No,14
2,ZYTJ,PRD10093,457,502,55,No,45
3,0T0P,PRD10092,329,378,72,No,49
4,BVM2,PRD10082,80,153,77,No,73

In [34]:
Inventory.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Site ID              100 non-null    str
 1   Product ID           100 non-null    str
 2   Beginning Inventory  100 non-null    int64
 3   Ending Inventory     100 non-null    int64
 4   Replenishment        100 non-null    int64
 5   Stockout Flag        100 non-null    str
 6   Net Stock            100 non-null    int64
dtypes: int64(4), str(3)
memory usage: 5.6 KB

In [36]:
cursor.execute(""" CREATE TABLE IF NOT EXISTS Inventory (
    Site_ID VARCHAR(20) NOT NULL,
    Product_ID VARCHAR(100) NOT NULL,
    Beginning_Inventory INT NOT NULL,
    Ending_Inventory INT NOT NULL,
    Replenishment INT NOT NULL,
    Stockout_Flag VARCHAR(10) NOT NULL,
    Net_Stock INT NOT NULL
)""")

connection.commit()

In [57]:
cursor.execute("SHOW TABLES")
for i in cursor.fetchall():
    print(i[0])

customer
inventory
logistics
product
site

In [58]:
cursor.execute("describe inventory")
for row in cursor.fetchall():
    print (row)

('Site_ID', 'varchar(20)', 'NO', '', None, '')
('Product_ID', 'varchar(100)', 'NO', '', None, '')
('Beginning_Inventory', 'int', 'NO', '', None, '')
('Ending_Inventory', 'int', 'NO', '', None, '')
('Replenishment', 'int', 'NO', '', None, '')
('Stockout_Flag', 'varchar(10)', 'NO', '', None, '')
('Net_Stock', 'int', 'NO', '', None, '')

In [43]:
Logisitics=pd.read_csv(r"C:\Users\ADMIN\Desktop\Retail_Analytics_Project\03_Cleaned_Data\Logistics_Data_Cleaned.csv")
Logisitics.head()

,Unnamed: 0,Shipment ID,Site ID,Product ID,Shipment Date,Quantity,Delivery Status,Transportation Type
0,0,SHP90000,7EEQ,PRD10038,2024-07-15,76,Cancelled,Rail
1,1,SHP90001,NY20,PRD10050,2024-08-30,92,Delivered,Rail
2,2,SHP90002,0L72,PRD10049,2024-05-28,40,Delayed,Truck
3,3,SHP90003,58KX,PRD10001,2024-10-02,50,Delivered,Ship
4,4,SHP90004,4ZKL,PRD10053,2024-10-05,79,Cancelled,Rail

In [49]:
Logisitics.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           150 non-null    int64
 1   Shipment ID          150 non-null    str
 2   Site ID              150 non-null    str
 3   Product ID           150 non-null    str
 4   Shipment Date        150 non-null    datetime64[us]
 5   Quantity             150 non-null    int64
 6   Delivery Status      150 non-null    str
 7   Transportation Type  150 non-null    str
dtypes: datetime64[us](1), int64(2), str(5)
memory usage: 9.5 KB

In [54]:
Logisitics["Shipment Date"]=pd.to_datetime(Logisitics["Shipment Date"],errors="coerce")

In [55]:
print(Logisitics.columns.tolist())

['Shipment ID', 'Site ID', 'Product ID', 'Shipment Date', 'Quantity', 'Delivery Status', 'Transportation Type']

In [59]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Logistics (
    Shipment_ID VARCHAR(20) PRIMARY KEY,
    Site_ID VARCHAR(20) NOT NULL,
    Product_ID VARCHAR(100) NOT NULL,
    Shipment_Date DATE NOT NULL,
    Quantity INT NOT NULL,
    Delivery_Status VARCHAR(50) NOT NULL,
    Transportation_Type VARCHAR(50) NOT NULL
)
""")

connection.commit()
print("Logistics table created successfully")

Logistics table created successfully

In [61]:
cursor.execute("describe logistics")
for row in cursor.fetchall():
    print (row)

('Shipment_ID', 'varchar(20)', 'NO', 'PRI', None, '')
('Site_ID', 'varchar(20)', 'NO', '', None, '')
('Product_ID', 'varchar(100)', 'NO', '', None, '')
('Shipment_Date', 'date', 'NO', '', None, '')
('Quantity', 'int', 'NO', '', None, '')
('Delivery_Status', 'varchar(50)', 'NO', '', None, '')
('Transportation_Type', 'varchar(50)', 'NO', '', None, '')

In [64]:
Promotion_Discount=pd.read_csv(r"C:\Users\ADMIN\Desktop\Retail_Analytics_Project\03_Cleaned_Data\Promotions_and_Discounts_Cleaned.csv")
Promotion_Discount.head()

,Promotion ID,Product ID,Site ID,Start Date,End Date,Discount Type,Discount Amount
0,PROMO10000,PRD10033,CXUL,2024-08-29,2024-12-25,Percentage,20.00
1,PROMO10001,PRD10081,30T9,2024-05-07,2025-01-03,Percentage,21.00
2,PROMO10002,PRD10087,H75L,2024-10-13,2025-02-25,Flat,23.59
3,PROMO10003,PRD10017,FFYV,2024-07-12,2025-01-03,Flat,49.42
4,PROMO10004,PRD10018,T4UF,2024-09-09,2025-03-11,Percentage,29.00

In [68]:
Promotion_Discount.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Promotion ID     50 non-null     str
 1   Product ID       50 non-null     str
 2   Site ID          50 non-null     str
 3   Start Date       50 non-null     str
 4   End Date         50 non-null     str
 5   Discount Type    50 non-null     str
 6   Discount Amount  50 non-null     float64
dtypes: float64(1), str(6)
memory usage: 2.9 KB

In [69]:
Promotion_Discount["Start Date"] = pd.to_datetime(
    Promotion_Discount["Start Date"],
    errors="coerce"
)

Promotion_Discount["End Date"] = pd.to_datetime(
    Promotion_Discount["End Date"],
    errors="coerce"
)

In [71]:
Promotion_Discount.dtypes

Promotion ID                  str
Product ID                    str
Site ID                       str
Start Date         datetime64[us]
End Date           datetime64[us]
Discount Type                 str
Discount Amount           float64
dtype: object

In [73]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Promotions_and_Discounts (
    Promotion_ID VARCHAR(20) PRIMARY KEY,
    Product_ID VARCHAR(100) NOT NULL,
    Site_ID VARCHAR(20) NOT NULL,
    Start_Date DATE NOT NULL,
    End_Date DATE NOT NULL,
    Discount_Type VARCHAR(20) NOT NULL,
    Discount_Amount FLOAT NOT NULL
)
""")

connection.commit()
print("Promotions_and_Discounts table created successfully")

Promotions_and_Discounts table created successfully

In [75]:
cursor.execute("SHOW TABLES")
for i in cursor.fetchall():
    print(i[0])

customer
inventory
logistics
product
promotions_and_discounts
site

In [77]:
cursor.execute("describe logistics")
for row in cursor.fetchall():
    print (row)

('Shipment_ID', 'varchar(20)', 'NO', 'PRI', None, '')
('Site_ID', 'varchar(20)', 'NO', '', None, '')
('Product_ID', 'varchar(100)', 'NO', '', None, '')
('Shipment_Date', 'date', 'NO', '', None, '')
('Quantity', 'int', 'NO', '', None, '')
('Delivery_Status', 'varchar(50)', 'NO', '', None, '')
('Transportation_Type', 'varchar(50)', 'NO', '', None, '')

In [84]:
Monthly_Seasonal_Planning=pd.read_csv(r"C:\Users\ADMIN\Desktop\Retail_Analytics_Project\03_Cleaned_Data\Monthly_Seasonal_Planning_Cleaned.csv")
Monthly_Seasonal_Planning.head()

,Month,Site ID,Product Category,Forecasted Sales,Actual Sales,Seasonal Adjustments,Difference
0,May-2024,PS3Y,Dairy,81260.50,96315.510888,0.1853,15055.010888
1,Dec-2024,W1Q5,Apparel,60609.93,64357.950697,0.0618,3748.020697
2,Sep-2024,T4UF,Apparel,84277.99,94950.573265,0.1266,10672.583265
3,Dec-2024,T4UF,Apparel,79067.48,82228.634271,0.0400,3161.154271
4,Mar-2025,OTOH,Apparel,50727.92,42559.446989,-0.1610,-8168.473011

In [85]:
Monthly_Seasonal_Planning.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Month                 120 non-null    str
 1   Site ID               120 non-null    str
 2   Product Category      120 non-null    str
 3   Forecasted Sales      120 non-null    float64
 4   Actual Sales          120 non-null    float64
 5   Seasonal Adjustments  120 non-null    float64
 6   Difference            120 non-null    float64
dtypes: float64(4), str(3)
memory usage: 6.7 KB

In [87]:
Monthly_Seasonal_Planning.dtypes

Month                       str
Site ID                     str
Product Category            str
Forecasted Sales        float64
Actual Sales            float64
Seasonal Adjustments    float64
Difference              float64
dtype: object

In [89]:
Monthly_Seasonal_Planning["Month"] = pd.to_datetime(
    Monthly_Seasonal_Planning["Month"],
    format="%b-%Y"
)

In [91]:
Monthly_Seasonal_Planning.dtypes

Month                   datetime64[us]
Site ID                            str
Product Category                   str
Forecasted Sales               float64
Actual Sales                   float64
Seasonal Adjustments           float64
Difference                     float64
dtype: object

In [93]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Monthly_Seasonal_Planning(
    Month DATE NOT NULL,
    Site_ID VARCHAR(20) NOT NULL,
    Product_Category VARCHAR(50) NOT NULL,
    Forecasted_Sales FLOAT NOT NULL,
    Actual_Sales FLOAT NOT NULL,
    Seasonal_Adjustments FLOAT NOT NULL,
    Difference FLOAT NOT NULL
)
""")

connection.commit()
print("Monthly_Seasonal_Planning table created successfully")

Monthly_Seasonal_Planning table created successfully

In [105]:
cursor.execute("SHOW TABLES")
for i in cursor.fetchall():
    print(i[0])

cursor.execute("describe Monthly_Seasonal_Planning ")
for row in cursor.fetchall():
    print (row)

customer
invalid_returns
inventory
logistics
monthly_seasonal_planning
product
promotions_and_discounts
site
('Month', 'date', 'NO', '', None, '')
('Site_ID', 'varchar(20)', 'NO', '', None, '')
('Product_Category', 'varchar(50)', 'NO', '', None, '')
('Forecasted_Sales', 'float', 'NO', '', None, '')
('Actual_Sales', 'float', 'NO', '', None, '')
('Seasonal_Adjustments', 'float', 'NO', '', None, '')
('Difference', 'float', 'NO', '', None, '')

In [ ]:

Invalid_Returns=pd.read_csv(r"C:\Users\ADMIN\Desktop\Retail_Analytics_Project\03_Cleaned_Data\Invalid_Returns_Cleaned.csv")

Invalid_Returns.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         4 non-null      str
 1   Site ID      4 non-null      str
 2   Product ID   4 non-null      str
 3   Units Sold   4 non-null      int64
 4   Revenue      4 non-null      float64
 5   Discounts    4 non-null      float64
 6   Returns      4 non-null      int64
 7   Customer ID  4 non-null      str
dtypes: float64(2), int64(2), str(4)
memory usage: 388.0 bytes

In [100]:
Invalid_Returns.head()

,Date,Site ID,Product ID,Units Sold,Revenue,Discounts,Returns,Customer ID
0,2024-07-20,P7Y6,PRD10045,4,177.04,21.99,5,CUST200019
1,2025-01-21,SV87,PRD10092,4,1200.36,90.72,5,CUST200032
2,2025-03-25,H75L,PRD10024,2,463.40,52.28,3,CUST200034
3,2025-05-08,H75L,PRD10024,2,463.40,52.28,3,CUST200034

In [102]:
Invalid_Returns["Date"]=pd.to_datetime(Invalid_Returns["Date"],errors="coerce")

In [103]:
Invalid_Returns.dtypes

Date           datetime64[us]
Site ID                   str
Product ID                str
Units Sold              int64
Revenue               float64
Discounts             float64
Returns                 int64
Customer ID               str
dtype: object

In [106]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Invalid_Returns(
    Date DATE NOT NULL,
    Site_ID VARCHAR(20) NOT NULL,
    Product_ID VARCHAR(100) NOT NULL,
    Units_Sold INT NOT NULL,
    Revenue FLOAT NOT NULL,
    Discounts FLOAT NOT NULL,
    Returns INT NOT NULL,
    Customer_ID VARCHAR(20) NOT NULL
)
""")

connection.commit()

print("Invalid_Returns table created successfully")

Invalid_Returns table created successfully

In [116]:
cursor.execute("SHOW TABLES")
for i in cursor.fetchall():
    print(i[0])

cursor.execute("describe Monthly_Seasonal_Planning ")
for row in cursor.fetchall():
    print (row)

customer
invalid_returns
inventory
logistics
monthly_seasonal_planning
product
promotions_and_discounts
sales
site
('Month', 'date', 'NO', '', None, '')
('Site_ID', 'varchar(20)', 'NO', '', None, '')
('Product_Category', 'varchar(50)', 'NO', '', None, '')
('Forecasted_Sales', 'float', 'NO', '', None, '')
('Actual_Sales', 'float', 'NO', '', None, '')
('Seasonal_Adjustments', 'float', 'NO', '', None, '')
('Difference', 'float', 'NO', '', None, '')

In [117]:
Sales=pd.read_csv(r"C:\Users\ADMIN\Desktop\Retail_Analytics_Project\03_Cleaned_Data\Sales_Data_Cleaned.csv")
Sales.head()

,Date,Site ID,Product ID,Units Sold,Revenue,Discounts,Returns,Customer ID
0,2024-04-02,XDP5,PRD10002,20,4844.84,764.83,3,CUST200026
1,2024-04-03,PS3Y,PRD10020,27,9001.49,1639.15,3,CUST200048
2,2024-04-09,8CGV,PRD10008,23,3122.03,463.83,0,CUST200025
3,2024-04-09,4CIY,PRD10070,38,11323.57,1275.45,1,CUST200048
4,2024-04-17,2VLP,PRD10019,44,10382.36,1096.84,3,CUST200040

In [112]:
Sales["Date"]=pd.to_datetime(Sales["Date"],errors="coerce")

In [113]:
Sales.dtypes

Date           datetime64[us]
Site ID                   str
Product ID                str
Units Sold              int64
Revenue               float64
Discounts             float64
Returns                 int64
Customer ID               str
dtype: object

In [118]:
cursor.execute("""CREATE TABLE Sales(
    Sales_ID INT AUTO_INCREMENT PRIMARY KEY,
    Date DATE NOT NULL,
    Site_ID VARCHAR(20) NOT NULL,
    Product_ID VARCHAR(100) NOT NULL,
    Units_Sold INT NOT NULL,
    Revenue FLOAT NOT NULL,
    Discounts FLOAT NOT NULL,
    Returns INT NOT NULL,
    Customer_ID VARCHAR(20) NOT NULL
)""")
connection.commit()
print("created successfully")

ProgrammingError: 1050 (42S01): Table 'sales' already exists

In [120]:
cursor.execute("SHOW TABLES")
for i in cursor.fetchall():
    print(i[0])

customer
invalid_returns
inventory
logistics
monthly_seasonal_planning
product
promotions_and_discounts
sales
site

In [121]:
cursor.execute("describe sales ")
for row in cursor.fetchall():
    print (row)

('Sales_ID', 'int', 'NO', 'PRI', None, 'auto_increment')
('Date', 'date', 'NO', '', None, '')
('Site_ID', 'varchar(20)', 'NO', '', None, '')
('Product_ID', 'varchar(100)', 'NO', '', None, '')
('Units_Sold', 'int', 'NO', '', None, '')
('Revenue', 'float', 'NO', '', None, '')
('Discounts', 'float', 'NO', '', None, '')
('Returns', 'int', 'NO', '', None, '')
('Customer_ID', 'varchar(20)', 'NO', '', None, '')