In [2]:

import mysql.connector
import pandas as pd


connection = mysql.connector.connect(host="localhost",
                                     
    user="root",
    password="12345" )
if connection.is_connected():
    print("sucessfully connected to sql")

sucessfully connected to sql

In [3]:
cursor=connection.cursor()
# create data base
cursor.execute("CREATE DATABASE if not exists Retail_Analytics_DB")
cursor.execute("USE Retail_Analytics_DB")

In [ ]:
product = pd.read_csv(
    r"C:\Users\ADMIN\Desktop\Retail_Analytics_Project\03_Cleaned_Data\Product_Data_Cleaned.csv"
)

In [ ]:
product.head()

,Product ID,Product Name,Category,Subcategory,Unit Cost,Unit Price,Supplier,Shelf Life
0,PRD10000,Cheese Item 0,Dairy,Cheese,127.63,143.90,Supplier 1,12
1,PRD10001,Bread Item 1,Bakery,Bread,422.83,570.20,Supplier 4,37
2,PRD10002,Accessories Item 2,Electronics,Accessories,74.91,110.80,Supplier 8,70
3,PRD10003,Men Item 3,Apparel,Men,310.83,461.74,Supplier 2,46
4,PRD10004,Men Item 4,Apparel,Men,297.77,438.18,Supplier 10,178

In [ ]:
product.head()

,Product ID,Product Name,Category,Subcategory,Unit Cost,Unit Price,Supplier,Shelf Life
0,PRD10000,Cheese Item 0,Dairy,Cheese,127.63,143.90,Supplier 1,12
1,PRD10001,Bread Item 1,Bakery,Bread,422.83,570.20,Supplier 4,37
2,PRD10002,Accessories Item 2,Electronics,Accessories,74.91,110.80,Supplier 8,70
3,PRD10003,Men Item 3,Apparel,Men,310.83,461.74,Supplier 2,46
4,PRD10004,Men Item 4,Apparel,Men,297.77,438.18,Supplier 10,178

In [ ]:
product.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product ID    100 non-null    str
 1   Product Name  100 non-null    str
 2   Category      100 non-null    str
 3   Subcategory   100 non-null    str
 4   Unit Cost     100 non-null    float64
 5   Unit Price    100 non-null    float64
 6   Supplier      100 non-null    str
 7   Shelf Life    100 non-null    int64
dtypes: float64(2), int64(1), str(5)
memory usage: 6.4 KB

In [ ]:
product.columns.tolist()

['Product ID',
 'Product Name',
 'Category',
 'Subcategory',
 'Unit Cost',
 'Unit Price',
 'Supplier',
 'Shelf Life']

In [ ]:
product.dtypes

Product ID          str
Product Name        str
Category            str
Subcategory         str
Unit Cost       float64
Unit Price      float64
Supplier            str
Shelf Life        int64
dtype: object

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Product (
    Product_ID VARCHAR(100) PRIMARY KEY,
    Product_Name VARCHAR(100) NOT NULL,
    Category VARCHAR(50) NOT NULL,
    Subcategory VARCHAR(50) NOT NULL,
    Unit_Cost FLOAT NOT NULL,
    Unit_Price FLOAT NOT NULL,
    Supplier VARCHAR(100) NOT NULL,
    Shelf_Life INT NOT NULL
)
""")
connection.commit()

In [ ]:
cursor.execute("SHOW TABLES")
for table in cursor:
    print(table)

('customer',)
('product',)

In [ ]:
cursor.execute("DESCRIBE Product")
for row in cursor.fetchall():
    print(row)

('Product_ID', 'varchar(100)', 'NO', 'PRI', None, '')
('Product_Name', 'varchar(100)', 'NO', '', None, '')
('Category', 'varchar(50)', 'NO', '', None, '')
('Subcategory', 'varchar(50)', 'NO', '', None, '')
('Unit_Cost', 'float', 'NO', '', None, '')
('Unit_Price', 'float', 'NO', '', None, '')
('Supplier', 'varchar(100)', 'NO', '', None, '')
('Shelf_Life', 'int', 'NO', '', None, '')

In [ ]:
Customer=pd.read_csv(r"C:\Users\ADMIN\Desktop\Retail_Analytics_Project\03_Cleaned_Data\Customer_Demographics_Cleaned.csv")

In [ ]:
Customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          50 non-null     int64
 1   Customer ID         50 non-null     str
 2   Age                 50 non-null     int64
 3   Gender              50 non-null     str
 4   Income Bracket      50 non-null     str
 5   Purchase Frequency  50 non-null     int64
 6   Average Spend       50 non-null     float64
dtypes: float64(1), int64(3), str(3)
memory usage: 2.9 KB

In [ ]:
Customer.head(
    
)

,Unnamed: 0,Customer ID,Age,Gender,Income Bracket,Purchase Frequency,Average Spend
0,0,CUST200000,29,Female,10 LPA,9,2248.08
1,1,CUST200001,56,Male,20+ LPA,7,1335.89
2,2,CUST200002,58,Other,10 LPA,9,1250.89
3,3,CUST200003,36,Male,10 LPA,6,4288.93
4,4,CUST200004,57,Male,10-20 LPA,1,2680.74

In [ ]:
Customer.dtypes

Unnamed: 0              int64
Customer ID               str
Age                     int64
Gender                    str
Income Bracket            str
Purchase Frequency      int64
Average Spend         float64
dtype: object

In [ ]:
cursor.execute("""CREATE TABLE IF NOT EXISTS Customer(Customer_ID varchar(20) PRIMARY KEY,
Age int,
Gender varchar(20),
Income_Bracket varchar(20),
Purchase_Frequency int,
Average_Spend float
)""")
connection.commit()

In [ ]:
cursor.execute("SHOW TABLES")
for table in cursor:
 print(table)

('customer',)
('product',)

In [ ]:
print(connection.is_connected())

True

In [ ]:
cursor.execute("DESCRIBE Customer")
for row in cursor.fetchall():
    print(row)

('Customer_ID', 'varchar(20)', 'NO', 'PRI', None, '')
('Age', 'int', 'NO', '', None, '')
('Gender', 'varchar(20)', 'NO', '', None, '')
('Income_Bracket', 'varchar(20)', 'NO', '', None, '')
('Purchase_Frequency', 'int', 'NO', '', None, '')
('Average_Spend', 'float', 'NO', '', None, '')

In [6]:
cursor.execute("DROP TABLE IF EXISTS Customer")
connection.commit()

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Customer (
    Customer_ID VARCHAR(20) PRIMARY KEY,
    Age INT NOT NULL,
    Gender VARCHAR(20) NOT NULL,
    Income_Bracket VARCHAR(20) NOT NULL,
    Purchase_Frequency INT NOT NULL,
    Average_Spend FLOAT NOT NULL
)
""")

connection.commit()

print("Customer table created successfully")

Customer table created successfully

In [ ]:
Site=pd.read_csv(r"C:\Users\ADMIN\Desktop\Retail_Analytics_Project\03_Cleaned_Data\Site_Details_Cleaned.csv")

In [ ]:
Site.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Site ID      50 non-null     str
 1   Site Name    50 non-null     str
 2   Site Format  50 non-null     str
 3   Region       50 non-null     str
 4   City         50 non-null     str
 5   State        50 non-null     str
 6   Store Size   50 non-null     int64
 7   Open Date    50 non-null     datetime64[us]
 8   Status       50 non-null     str
dtypes: datetime64[us](1), int64(1), str(7)
memory usage: 3.6 KB

In [ ]:
Site["Open Date"]=pd.to_datetime(Site["Open Date"],errors="coerce")

In [ ]:
Site.head()

,Site ID,Site Name,Site Format,Region,City,State,Store Size,Open Date,Status
0,JI0Y,Smart Mumbai,Digital,North,Mumbai,Maharashtra,6041,2015-05-03,Active
1,VUZZ,Digital Ahmedabad,Fresh,North,Ahmedabad,Gujarat,19719,2021-08-10,Inactive
2,PKH1,Smart Mumbai,Smart,North,Mumbai,Maharashtra,17449,2016-02-01,Inactive
3,30T9,Digital Hubli,Smart,South,Hubli,Karnataka,23089,2018-04-15,Inactive
4,CX19,Fresh New Delhi,Smart,North,New Delhi,Delhi,17455,2018-02-12,Inactive

In [ ]:
Site.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Site ID      50 non-null     str
 1   Site Name    50 non-null     str
 2   Site Format  50 non-null     str
 3   Region       50 non-null     str
 4   City         50 non-null     str
 5   State        50 non-null     str
 6   Store Size   50 non-null     int64
 7   Open Date    50 non-null     datetime64[us]
 8   Status       50 non-null     str
dtypes: datetime64[us](1), int64(1), str(7)
memory usage: 3.6 KB

In [ ]:
cursor.execute("DROP TABLE IF EXISTS SITE")
connection.commit()

In [ ]:
cursor.execute(""" CREATE TABLE IF NOT EXISTS SITE(
Site_ID VARCHAR(20) PRIMARY KEY,
Site_Name VARCHAR(20) NOT NULL,
Site_Format VARCHAR(20) NOT NULL,
Region VARCHAR(20) NOT NULL,
City VARCHAR(20) NOT NULL,
State VARCHAR(20) NOT NULL,
Store_Size VARCHAR(20) NOT NULL,
Open_Date Date NOT NULL,
Status VARCHAR(20))"""

)

In [ ]:
connection.commit()

In [7]:
cursor.execute("SHOW TABLES")
for table in cursor.fetchall():
    print(table)

('product',)
('site',)

In [8]:
cursor.execute("DESCRIBE Site")
for row in cursor.fetchall():
    print(row)

('Site_ID', 'varchar(20)', 'NO', 'PRI', None, '')
('Site_Name', 'varchar(20)', 'NO', '', None, '')
('Site_Format', 'varchar(20)', 'NO', '', None, '')
('Region', 'varchar(20)', 'NO', '', None, '')
('City', 'varchar(20)', 'NO', '', None, '')
('State', 'varchar(20)', 'NO', '', None, '')
('Store_Size', 'varchar(20)', 'NO', '', None, '')
('Open_Date', 'date', 'NO', '', None, '')
('Status', 'varchar(20)', 'YES', '', None, '')