In [2]:

import mysql.connector
import pandas as pd


connection = mysql.connector.connect(host="localhost",
                                     
    user="root",
    password="12345" )
if connection.is_connected():
    print("sucessfully connected to sql")

sucessfully connected to sql

In [3]:
cursor=connection.cursor()
# create data base
cursor.execute("CREATE DATABASE if not exists Retail_Analytics_DB")
cursor.execute("USE Retail_Analytics_DB")

In [5]:
product = pd.read_csv(
    r"C:\Users\ADMIN\Desktop\Retail_Analytics_Project\03_Cleaned_Data\Product_Data_Cleaned.csv"
)

In [6]:
product.head()

,Product ID,Product Name,Category,Subcategory,Unit Cost,Unit Price,Supplier,Shelf Life
0,PRD10000,Cheese Item 0,Dairy,Cheese,127.63,143.90,Supplier 1,12
1,PRD10001,Bread Item 1,Bakery,Bread,422.83,570.20,Supplier 4,37
2,PRD10002,Accessories Item 2,Electronics,Accessories,74.91,110.80,Supplier 8,70
3,PRD10003,Men Item 3,Apparel,Men,310.83,461.74,Supplier 2,46
4,PRD10004,Men Item 4,Apparel,Men,297.77,438.18,Supplier 10,178

In [8]:
product.head()

,Product ID,Product Name,Category,Subcategory,Unit Cost,Unit Price,Supplier,Shelf Life
0,PRD10000,Cheese Item 0,Dairy,Cheese,127.63,143.90,Supplier 1,12
1,PRD10001,Bread Item 1,Bakery,Bread,422.83,570.20,Supplier 4,37
2,PRD10002,Accessories Item 2,Electronics,Accessories,74.91,110.80,Supplier 8,70
3,PRD10003,Men Item 3,Apparel,Men,310.83,461.74,Supplier 2,46
4,PRD10004,Men Item 4,Apparel,Men,297.77,438.18,Supplier 10,178

In [7]:
product.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product ID    100 non-null    str
 1   Product Name  100 non-null    str
 2   Category      100 non-null    str
 3   Subcategory   100 non-null    str
 4   Unit Cost     100 non-null    float64
 5   Unit Price    100 non-null    float64
 6   Supplier      100 non-null    str
 7   Shelf Life    100 non-null    int64
dtypes: float64(2), int64(1), str(5)
memory usage: 6.4 KB

In [8]:
product.columns.tolist()

['Product ID',
 'Product Name',
 'Category',
 'Subcategory',
 'Unit Cost',
 'Unit Price',
 'Supplier',
 'Shelf Life']

In [9]:
product.dtypes

Product ID          str
Product Name        str
Category            str
Subcategory         str
Unit Cost       float64
Unit Price      float64
Supplier            str
Shelf Life        int64
dtype: object

In [11]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Product (
    Product_ID VARCHAR(100) PRIMARY KEY,
    Product_Name VARCHAR(100) NOT NULL,
    Category VARCHAR(50) NOT NULL,
    Subcategory VARCHAR(50) NOT NULL,
    Unit_Cost FLOAT NOT NULL,
    Unit_Price FLOAT NOT NULL,
    Supplier VARCHAR(100) NOT NULL,
    Shelf_Life INT NOT NULL
)
""")
connection.commit()

In [13]:
cursor.execute("SHOW TABLES")
for table in cursor:
    print(table)

('product',)

In [14]:
cursor.execute("DESCRIBE Product")
for row in cursor.fetchall():
    print(row)

('Product_ID', 'varchar(100)', 'NO', 'PRI', None, '')
('Product_Name', 'varchar(100)', 'NO', '', None, '')
('Category', 'varchar(50)', 'NO', '', None, '')
('Subcategory', 'varchar(50)', 'NO', '', None, '')
('Unit_Cost', 'float', 'NO', '', None, '')
('Unit_Price', 'float', 'NO', '', None, '')
('Supplier', 'varchar(100)', 'NO', '', None, '')
('Shelf_Life', 'int', 'NO', '', None, '')