In [56]:
import pandas as py
customer_demographic=py.read_csv("../02_Raw_Data/Customer_Demographics.csv")
print(customer_demographic.head().to_string())

  Customer ID  Age  Gender Income Bracket  Purchase Frequency  Average Spend
0  CUST200000   29  Female         10 LPA                   9        2248.08
1  CUST200001   56    Male        20+ LPA                   7        1335.89
2  CUST200002   58   Other         10 LPA                   9        1250.89
3  CUST200003   36    Male         10 LPA                   6        4288.93
4  CUST200004   57    Male      10-20 LPA                   1        2680.74

In [57]:
#customer_demographic
#1 shape
print(customer_demographic.shape)

#2 describe
print(customer_demographic.describe())

#3 cloumns

print(customer_demographic.columns)

#4 info

print(customer_demographic.info())

#5 duplicate 


print(customer_demographic.duplicated().sum())

(50, 6)
             Age  Purchase Frequency  Average Spend
count  50.000000           50.000000      50.000000
mean   44.060000            6.440000    2825.569000
std    13.902591            3.540783    1304.316051
min    18.000000            1.000000     620.710000
25%    33.000000            3.250000    1827.242500
50%    43.500000            7.000000    2762.425000
75%    56.750000            9.000000    3975.290000
max    69.000000           12.000000    4963.270000
Index(['Customer ID', 'Age', 'Gender', 'Income Bracket', 'Purchase Frequency',
       'Average Spend'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer ID         50 non-null     str
 1   Age                 50 non-null     int64
 2   Gender              50 non-null     str
 3   Income Bracket      50 non-null     str
 4   Purchase Frequency  50 non-null     int64
 5   Average Spend       50 non-null     float64
dtypes: float64(1), int64(2), str(3)
memory usage: 2.5 KB
None
0

In [58]:
#6 unquie
print(customer_demographic["Customer ID"].nunique())

#7 isnull
print(customer_demographic[["Customer ID","Age","Gender","Income Bracket","Purchase Frequency","Average Spend"]].isnull().sum()
)
#8 TO LIST
print(customer_demographic.columns.tolist())
# 9 IS NULL SUM
print(customer_demographic.isnull().sum())

50
Customer ID           0
Age                   0
Gender                0
Income Bracket        0
Purchase Frequency    0
Average Spend         0
dtype: int64
['Customer ID', 'Age', 'Gender', 'Income Bracket', 'Purchase Frequency', 'Average Spend']
Customer ID           0
Age                   0
Gender                0
Income Bracket        0
Purchase Frequency    0
Average Spend         0
dtype: int64

In [59]:
# values of counts

print(customer_demographic["Gender"].value_counts())

# remove extra space
customer_demographic.columns = customer_demographic.columns.str.strip()
print(customer_demographic.columns)

# validation income bracke
print(customer_demographic["Income Bracket"].value_counts())
print((customer_demographic["Purchase Frequency"] <= 0).sum() )

Gender
Male      24
Other     16
Female    10
Name: count, dtype: int64
Index(['Customer ID', 'Age', 'Gender', 'Income Bracket', 'Purchase Frequency',
       'Average Spend'],
      dtype='str')
Income Bracket
10 LPA       14
20+ LPA      14
10-20 LPA    13
1-5 LPA       9
Name: count, dtype: int64
0

In [60]:
print((customer_demographic["Average Spend"] <= 0).sum() )
print((customer_demographic["Average Spend"] <= 0).all () )
print((customer_demographic["Average Spend"] <= 0).any () )

0
False
False

In [61]:
customer_demographic[(customer_demographic["Age"])<18| (customer_demographic["Age"]>100)]

Empty DataFrame
Columns: [Customer ID, Age, Gender, Income Bracket, Purchase Frequency, Average Spend]
Index: []

In [64]:
#Customer ID Duplicate Check

customer_demographic[
    customer_demographic["Customer ID"].duplicated(keep=False)
]

Empty DataFrame
Columns: [Customer ID, Age, Gender, Income Bracket, Purchase Frequency, Average Spend]
Index: []

In [66]:
#Gender Validation
customer_demographic[customer_demographic["Gender"].isin(["Male","Female","Other"])]

   Customer ID  Age  Gender Income Bracket  Purchase Frequency  Average Spend
0   CUST200000   29  Female         10 LPA                   9        2248.08
1   CUST200001   56    Male        20+ LPA                   7        1335.89
2   CUST200002   58   Other         10 LPA                   9        1250.89
3   CUST200003   36    Male         10 LPA                   6        4288.93
4   CUST200004   57    Male      10-20 LPA                   1        2680.74
5   CUST200005   30  Female        20+ LPA                   7        3581.14
6   CUST200006   44   Other        20+ LPA                   8        1252.64
7   CUST200007   54    Male         10 LPA                   5         647.13
8   CUST200008   32   Other      10-20 LPA                   3        4013.33
9   CUST200009   54   Other        20+ LPA                   9        2798.63
10  CUST200010   54    Male      10-20 LPA                   9        4204.77
11  CUST200011   41   Other        1-5 LPA                  12        2486.15
12  CUST200012   31  Female        1-5 LPA                  12        4235.32
13  CUST200013   66    Male      10-20 LPA                   1        2523.80
14  CUST200014   40    Male        20+ LPA                   2        3990.34
15  CUST200015   33    Male      10-20 LPA                  12        3246.18
16  CUST200016   45    Male         10 LPA                   4        4160.88
17  CUST200017   69    Male      10-20 LPA                   9        1764.88
18  CUST200018   52    Male      10-20 LPA                  12        1816.86
19  CUST200019   54  Female        1-5 LPA                   3        4832.47
20  CUST200020   68  Female        1-5 LPA                   5        4401.71
21  CUST200021   26   Other         10 LPA                   4        1158.10
22  CUST200022   38    Male        20+ LPA                   8        1139.77
23  CUST200023   58  Female        20+ LPA                   7        2533.96
24  CUST200024   58    Male        20+ LPA                   9        3874.11
25  CUST200025   62  Female        20+ LPA                   8        1972.80
26  CUST200026   18   Other        1-5 LPA                  12        4874.68
27  CUST200027   58   Other      10-20 LPA                   2        4080.55
28  CUST200028   43    Male        20+ LPA                   4        2726.22
29  CUST200029   38  Female      10-20 LPA                   9        3100.70
30  CUST200030   54  Female      10-20 LPA                  11        3930.14
31  CUST200031   20    Male        20+ LPA                   1        1059.07
32  CUST200032   28  Female        20+ LPA                   1        4963.27
33  CUST200033   45    Male         10 LPA                  11        1858.39
34  CUST200034   35    Male      10-20 LPA                   5         870.89
35  CUST200035   60   Other         10 LPA                   1        2283.54
36  CUST200036   37   Other         10 LPA                   7        3449.68
37  CUST200037   63    Male        1-5 LPA                   4        2645.63
38  CUST200038   26   Other         10 LPA                   9        3559.92
39  CUST200039   18    Male      10-20 LPA                   2        4946.70
40  CUST200040   45   Other         10 LPA                   8         818.73
41  CUST200041   42    Male        1-5 LPA                   2        1910.08
42  CUST200042   37    Male        20+ LPA                   3        3387.09
43  CUST200043   61    Male        1-5 LPA                   9        3034.81
44  CUST200044   57   Other         10 LPA                   8        2080.34
45  CUST200045   31   Other         10 LPA                   7        3272.34
46  CUST200046   46    Male        1-5 LPA                   2        1130.06
47  CUST200047   25   Other        20+ LPA                   6        4834.62
48  CUST200048   38    Male         10 LPA                   5        3400.79
49  CUST200049   33   Other      10-20 LPA                  12         620.71

In [77]:
gen=["Male","Female","Other"]
(customer_demographic["Gender"].isin(gen)).sum()

np.int64(50)

In [78]:
valid_income = [
    "1-5 LPA",
    "10 LPA",
    "10-20 LPA",
    "20+ LPA"
]

customer_demographic[
    ~customer_demographic["Income Bracket"].isin(valid_income)
]

Empty DataFrame
Columns: [Customer ID, Age, Gender, Income Bracket, Purchase Frequency, Average Spend]
Index: []

In [80]:
customer_demographic.sort_values(
    "Average Spend",
    ascending=False
).head(10)

   Customer ID  Age  Gender Income Bracket  Purchase Frequency  Average Spend
32  CUST200032   28  Female        20+ LPA                   1        4963.27
39  CUST200039   18    Male      10-20 LPA                   2        4946.70
26  CUST200026   18   Other        1-5 LPA                  12        4874.68
47  CUST200047   25   Other        20+ LPA                   6        4834.62
19  CUST200019   54  Female        1-5 LPA                   3        4832.47
20  CUST200020   68  Female        1-5 LPA                   5        4401.71
3   CUST200003   36    Male         10 LPA                   6        4288.93
12  CUST200012   31  Female        1-5 LPA                  12        4235.32
10  CUST200010   54    Male      10-20 LPA                   9        4204.77
16  CUST200016   45    Male         10 LPA                   4        4160.88

In [83]:
#Remove Spaces from Text Columns

text_cols = [
    "Customer ID",
    "Gender",
    "Income Bracket"
]

for col in text_cols:
    customer_demographic[col] = customer_demographic[col].str.strip()

In [85]:
print(customer_demographic.info())

print(customer_demographic.describe())

print(customer_demographic.head())

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer ID         50 non-null     str
 1   Age                 50 non-null     int64
 2   Gender              50 non-null     str
 3   Income Bracket      50 non-null     str
 4   Purchase Frequency  50 non-null     int64
 5   Average Spend       50 non-null     float64
dtypes: float64(1), int64(2), str(3)
memory usage: 2.5 KB
None
             Age  Purchase Frequency  Average Spend
count  50.000000           50.000000      50.000000
mean   44.060000            6.440000    2825.569000
std    13.902591            3.540783    1304.316051
min    18.000000            1.000000     620.710000
25%    33.000000            3.250000    1827.242500
50%    43.500000            7.000000    2762.425000
75%    56.750000            9.000000    3975.290000
max    69.000000           12.000000    4963.270000
  Customer ID  Age  Gender Income Bracket  Purchase Frequency  Average Spend
0  CUST200000   29  Female         10 LPA                   9        2248.08
1  CUST200001   56    Male        20+ LPA                   7        1335.89
2  CUST200002   58   Other         10 LPA                   9        1250.89
3  CUST200003   36    Male         10 LPA                   6        4288.93
4  CUST200004   57    Male      10-20 LPA                   1        2680.74

In [86]:
customer_demographic.to_csv("../03_Cleaned_Data/Customer_Demographics_Cleaned.csv")

## Conclusion

- Total Customers : 50
- No Missing Values
- No Duplicate Records
- Customer IDs are Unique
- Gender values validated
- Income Brackets validated
- Purchase Frequency validated
- Average Spend validated
- Dataset is clean and ready for SQL & Power BI.