In [1]:
import pandas as py
inventory =py.read_csv(r"C:\Users\ADMIN\Desktop\Retail_Analytics_Project\02_Raw_Data\Inventory_Data.csv")
print(inventory.head().to_string())

  Site ID Product ID  Beginning Inventory  Ending Inventory  Replenishment Stockout Flag
0    A11D   PRD10087                  222               233             42            No
1    AM14   PRD10082                  428               442             72            No
2    ZYTJ   PRD10093                  457               502             55            No
3    0T0P   PRD10092                  329               378             72            No
4    BVM2   PRD10082                   80               153             77            No

In [2]:
print(" information of inventory")
print(inventory.info())

print("shape of the inventory")
print(inventory.shape)

print("describe the data set")
print(inventory.describe())

print(" checking null values")
print(inventory.isnull().sum())
print(inventory["Site ID"].isnull().sum())
print(inventory["Product ID"].isnull().sum())

print("unique value is site id, pro id")
print(inventory["Site ID"].nunique())
print(inventory["Product ID"].nunique())

print("checking Stockout Flag")
print(inventory.value_counts().sum())

 information of inventory
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Site ID              100 non-null    str
 1   Product ID           100 non-null    str
 2   Beginning Inventory  100 non-null    int64
 3   Ending Inventory     100 non-null    int64
 4   Replenishment        100 non-null    int64
 5   Stockout Flag        100 non-null    str
dtypes: int64(3), str(3)
memory usage: 4.8 KB
None
shape of the inventory
(100, 6)
describe the data set
       Beginning Inventory  Ending Inventory  Replenishment
count           100.000000        100.000000     100.000000
mean            259.880000        290.520000      60.790000
std             131.832024        132.074625      27.266472
min              53.000000         77.000000      10.000000
25%             149.500000        181.500000      41.250000
50%             244.500000        274.000000      60.500000
75%             368.500000        387.000000      84.000000
max             495.000000        565.000000     100.000000
 checking null values
Site ID                0
Product ID             0
Beginning Inventory    0
Ending Inventory       0
Replenishment          0
Stockout Flag          0
dtype: int64
0
0
unique value is site id, pro id
45
65
checking Stockout Flag
100

In [3]:
inventory["Net Stock"]=inventory["Ending Inventory"]-inventory["Beginning Inventory"]
print(f"{inventory.head()}")

  Site ID Product ID  Beginning Inventory  Ending Inventory  Replenishment  \
0    A11D   PRD10087                  222               233             42
1    AM14   PRD10082                  428               442             72
2    ZYTJ   PRD10093                  457               502             55
3    0T0P   PRD10092                  329               378             72
4    BVM2   PRD10082                   80               153             77

  Stockout Flag  Net Stock
0            No         11
1            No         14
2            No         45
3            No         49
4            No         73

In [4]:
inventory["Stockout Flag"].value_counts()

Stockout Flag
No    100
Name: count, dtype: int64

In [5]:
print(inventory.duplicated().sum())

0

In [6]:
print("checking the negative value")
print((inventory["Beginning Inventory"]< 0).sum())
print((inventory["Ending Inventory"]< 0).sum())
print((inventory["Replenishment"]< 0).sum())

checking the negative value
0
0
0

In [7]:
inventory.sort_values(
    "Net Stock"
).head()

,Site ID,Product ID,Beginning Inventory,Ending Inventory,Replenishment,Stockout Flag,Net Stock
91,OTOH,PRD10027,155,155,45,No,0
79,M5IG,PRD10053,93,94,24,No,1
29,BVM2,PRD10042,246,248,27,No,2
84,VUZZ,PRD10043,381,383,23,No,2
72,ZYTJ,PRD10082,363,366,15,No,3

In [8]:
inventory[~inventory["Stockout Flag"].isin(["Yes","No"])]

Empty DataFrame
Columns: [Site ID, Product ID, Beginning Inventory, Ending Inventory, Replenishment, Stockout Flag, Net Stock]
Index: []

In [9]:
text_column=["Site ID","Product ID","Stockout Flag"]
for col in text_column:
    inventory[col]=inventory[col].str.strip()
print(inventory.head())

  Site ID Product ID  Beginning Inventory  Ending Inventory  Replenishment  \
0    A11D   PRD10087                  222               233             42
1    AM14   PRD10082                  428               442             72
2    ZYTJ   PRD10093                  457               502             55
3    0T0P   PRD10092                  329               378             72
4    BVM2   PRD10082                   80               153             77

  Stockout Flag  Net Stock
0            No         11
1            No         14
2            No         45
3            No         49
4            No         73

In [10]:
inventory.to_csv(
"../03_Cleaned_Data/Inventory_Data_Cleaned.csv",
index=False
)

## Inventory Dataset Validation

- Total Records: XXX
- No Missing Values
- No Duplicate Records
- Site IDs Validated
- Product IDs Validated
- Beginning Inventory Validated
- Ending Inventory Validated
- Replenishment Validated
- Stockout Flag Validated
- Net Stock Calculated
- Dataset Ready for SQL & Power BI