In [1]:
import pandas as pd
Promotion=pd.read_csv(r"C:\Users\ADMIN\Desktop\Retail_Analytics_Project\02_Raw_Data\Promotions_and_Discounts.csv")
Promotion.head()

,Promotion ID,Product ID,Site ID,Start Date,End Date,Discount Type,Discount Amount
0,PROMO10000,PRD10033,CXUL,2024-08-29,2024-12-25,Percentage,20.00
1,PROMO10001,PRD10081,30T9,2024-05-07,2025-01-03,Percentage,21.00
2,PROMO10002,PRD10087,H75L,2024-10-13,2025-02-25,Flat,23.59
3,PROMO10003,PRD10017,FFYV,2024-07-12,2025-01-03,Flat,49.42
4,PROMO10004,PRD10018,T4UF,2024-09-09,2025-03-11,Percentage,29.00

In [2]:
print("Shape")
print(Promotion.shape)

print("\nColumns")
print(Promotion.columns.tolist())

print("\nData Types")
print(Promotion.dtypes)

print("\nInfo")
Promotion.info()

Shape
(50, 7)

Columns
['Promotion ID', 'Product ID', 'Site ID', 'Start Date', 'End Date', 'Discount Type', 'Discount Amount']

Data Types
Promotion ID           str
Product ID             str
Site ID                str
Start Date             str
End Date               str
Discount Type          str
Discount Amount    float64
dtype: object

Info
<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Promotion ID     50 non-null     str
 1   Product ID       50 non-null     str
 2   Site ID          50 non-null     str
 3   Start Date       50 non-null     str
 4   End Date         50 non-null     str
 5   Discount Type    50 non-null     str
 6   Discount Amount  50 non-null     float64
dtypes: float64(1), str(6)
memory usage: 2.9 KB

In [3]:
print("Missing Values")
print(Promotion.isnull().sum())

print("\nDuplicate Rows")
print(Promotion.duplicated().sum())

print("\nUnique Values")
print(Promotion.nunique())

Missing Values
Promotion ID       0
Product ID         0
Site ID            0
Start Date         0
End Date           0
Discount Type      0
Discount Amount    0
dtype: int64

Duplicate Rows
0

Unique Values
Promotion ID       50
Product ID         40
Site ID            32
Start Date         44
End Date           45
Discount Type       2
Discount Amount    45
dtype: int64

In [7]:
Promotion.columns = Promotion.columns.str.strip()

In [8]:
Promotion.describe()

       Discount Amount
count        50.000000
mean         24.454400
std          12.928773
min           5.000000
25%          13.527500
50%          23.370000
75%          34.845000
max          49.420000

In [10]:
print("Negative Discount")
print((Promotion["Discount Amount"] < 0).sum())

print("Discount > 100")
print((Promotion["Discount Amount"] > 100).sum())

Negative Discount
0
Discount > 100
0

In [11]:
Promotion["Start Date"] = pd.to_datetime(Promotion["Start Date"], errors="coerce")
Promotion["End Date"] = pd.to_datetime(Promotion["End Date"], errors="coerce")

In [13]:
Promotion["Start Date"].isnull().sum()
Promotion["End Date"].isnull().sum()

np.int64(0)

In [14]:
print(Promotion["Promotion ID"].nunique())
print(Promotion["Promotion ID"].duplicated().sum())

50
0

In [15]:
Promotion.columns.tolist()

['Promotion ID',
 'Product ID',
 'Site ID',
 'Start Date',
 'End Date',
 'Discount Type',
 'Discount Amount']

In [16]:
print(Promotion.info())

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Promotion ID     50 non-null     str
 1   Product ID       50 non-null     str
 2   Site ID          50 non-null     str
 3   Start Date       50 non-null     datetime64[us]
 4   End Date         50 non-null     datetime64[us]
 5   Discount Type    50 non-null     str
 6   Discount Amount  50 non-null     float64
dtypes: datetime64[us](2), float64(1), str(4)
memory usage: 2.9 KB
None

In [17]:
valid_discount = ["Percentage","Flat"]

Promotion[
    ~Promotion["Discount Type"].isin(valid_discount)
]

Empty DataFrame
Columns: [Promotion ID, Product ID, Site ID, Start Date, End Date, Discount Type, Discount Amount]
Index: []

In [18]:
print("Promotion Dataset Validation")

print("Rows                :", Promotion.shape[0])
print("Columns             :", Promotion.shape[1])
print("Duplicate Rows      :", Promotion.duplicated().sum())
print("Missing Values      :", Promotion.isnull().sum().sum())
print("Unique Promotion IDs:", Promotion["Promotion ID"].nunique())
print("Negative Discount   :", (Promotion["Discount Amount"] < 0).sum())
print("Discount > 100      :", (Promotion["Discount Amount"] > 100).sum())

Promotion Dataset Validation
Rows                : 50
Columns             : 7
Duplicate Rows      : 0
Missing Values      : 0
Unique Promotion IDs: 50
Negative Discount   : 0
Discount > 100      : 0

In [19]:
Promotion.to_csv(
    r"C:\Users\ADMIN\Desktop\Retail_Analytics_Project\03_Cleaned_Data\Promotions_and_Discounts_Cleaned.csv",
    index=False
)

## Promotion & Discount Data Validation

- Total Records: 50
- No Missing Values
- No Duplicate Rows
- Promotion ID Unique
- Dates Converted Successfully
- End Date Validated
- Discount Types Validated
- Discount Amount Validated
- No Invalid Discounts
- Dataset Ready for SQL & Power BI